short_title: "[L]Electrek ASC 2024"
email: jonathan_mullen@americansolarchallenge.org
baseurl: "" # the subpath of your site, e.g. /blog
url: 'http://127.0.0.1:4000/' # the base hostname & protocol for your site
