# site settings
title: Electrek American Solar Challenge 2024
subtitle: 
email: ascwebmaster@americansolarchallenge.org
short_title: Electrek ASC 2024
description: See results here
baseurl: "/2024/results" # the subpath of your site, e.g. /blog
url: 'https://www.americansolarchallenge.org' # the base hostname & protocol for your site
imagepath: "/assets/images"
author:
copyright:
  year: 2024
  org: Innovators Educational Foundation
disclaimer: FSGP is not associated with Formula 1 Racing
# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

fsgp-days-tabs: false

timezone: America/Chicago

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub:
  GitLab:
  Google-Plus:
  Instagram: https://www.instagram.com/americansolarchallenge/
  LinkedIn: "https://www.linkedin.com/company/innovators-educational-foundation"
  Twitter: "https://twitter.com/ASC_SolarRacing"
  Facebook: "https://www.facebook.com/AmericanSolarChallenge"
  Slack:
  Flickr: "https://www.flickr.com/photos/americansolarchallenge/"
  YouTube: "https://www.youtube.com/@AmericanSolarChallenge"


collections:
  teams: 
    output: true
    sort_by: number
    permalink: /teams/:name

# build settings
markdown: kramdown

defaults:
  -
    scope:
      path: ""
      type: "teams" # a collection in your site, in plural form
    values:
      layout: "page-team"

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 

plugins:
    - jekyll-asciidoc
    - jekyll-gist
    - jekyll-paginate
    - jekyll-tabs
