subtitle: "GH Staging"
email: jonathan_mullen@americansolarchallenge.org
baseurl: "/asc-fsgp-2024-results" # the subpath of your site, e.g. /blog
url: 'https://jtmullen.github.io' # the base hostname & protocol for your site
data_dir: _data_dummy

