name: Deploy to ASC From Push

on:
  push:
    branches:
      - main


jobs: 
    asc-site-deploy:
        permissions:
            contents: write
        uses: ./.github/workflows/asc-site.yml
        secrets: inherit