name: Check for broken links
on: 
  workflow_dispatch: # allow manual trigger
  schedule:
    # run daily at 4 am
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 4 * * *'
jobs:
  crawl_for_broken_links:
    runs-on: ubuntu-latest
    name: Broken-Links-Crawler
    steps:
    - name: Checking links
      uses: ScholliYT/Broken-Links-Crawler-Action@v3
      with:
        website_url: 'https://www.americansolarchallenge.org/2024/'
        exclude_url_prefix: 'mailto:,https://www.linkedin.com,https://linkedin.com,https://www.twitter.com,http://www.twitter.com,https://www.x.com,http://www.x.com'
        exclude_url_contained: 'twitter,maps/embed,nhtcf,'
        verbose: 'true'
        max_retry_time: 30
        max_retries: 5
        max_depth: -1