name: Update Results Status

on: 
    repository_dispatch:
        types: [results]
        

jobs:
    results-update:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        timeout-minutes: 5
        steps:
            - name: Log Info
              run: |
                echo "Time: ${{ github.event.client_payload.time }}"
                echo "Publish Update: ${{ github.event.client_payload.update }}"
                echo "SOV: ${{ github.event.client_payload.sov }}; MOV: ${{ github.event.client_payload.mov }}; Score: ${{ github.event.client_payload.score }}"
                echo "SOV Data: ${{ github.event.client_payload.sov_data }}"
                echo "MOV Data: ${{ github.event.client_payload.mov_data }}"
                echo "Score Data: ${{ github.event.client_payload.score_data }}"
            - uses: actions/checkout@v3
              with: 
                ref: 'dev'
              name: Checkout Repo
            - name: Generate New SOV CSV File
              if: ${{ github.event.client_payload.sov }}
              run: |
                cd $GITHUB_WORKSPACE
                cd _data
                echo -n $'${{ github.event.client_payload.sov_data }}' > sov.csv
            - name: Generate New MOV CSV File
              if: ${{ github.event.client_payload.mov }}
              run: |
                cd $GITHUB_WORKSPACE
                cd _data
                echo -n $'${{ github.event.client_payload.mov_data }}' > mov.csv
            - name: Generate New Score CSV File
              if: ${{ github.event.client_payload.score }}
              run: |
                cd $GITHUB_WORKSPACE
                cd _data
                echo -n $'${{ github.event.client_payload.score_data }}' > mov-score.csv
            - name: Add SOV Update
              if: ${{ github.event.client_payload.update }} &&  ${{ github.event.client_payload.sov }}
              uses: ./.github/actions/generate-update
              with: 
                board: sov
                time: ${{ github.event.client_payload.time }}
            - name: Add MOV Update
              if: ${{ github.event.client_payload.update }} &&  ${{ github.event.client_payload.mov }}
              uses: ./.github/actions/generate-update
              with: 
                board: mov
                time: ${{ github.event.client_payload.time }}
                score: ${{ github.event.client_payload.score }}
            - name: Push to Git
              run: |
                git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
                git config --global user.name "github-actions[bot]"
                git add *
                git commit -m"[BOT] Scrutineering Update ${GITHUB_RUN_ID}"
                git push
    github-pages-deploy:
        concurrency: website-update
        runs-on: ubuntu-latest
        needs: [results-update]
        permissions:
            contents: write
        steps:
          - name: Checkout Source Repo
            uses: actions/checkout@v2
            with: 
                ref: 'dev'
          - name: Build
            uses:  jeffreytse/jekyll-deploy-action@v0.3.1
            with:
              provider: 'github'
              token: ${{ secrets.GITHUB_TOKEN }}
              branch: 'gh-pages'
              jekyll_cfg: "_config_deploy.yml,_config_gh_pages.yml"
