name: Update Scrutineering Status

on: 
    repository_dispatch:
        types: [scrutineering]
        

jobs:
    scutineering-update:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        timeout-minutes: 5
        steps:
            - uses: actions/checkout@v3
              with: 
                ref: 'dev'
              name: Checkout Repo
            - name: Generate New CSV File
              run: |
                cd $GITHUB_WORKSPACE
                cd _data
                echo -n $'${{ github.event.client_payload.data }}' > scrutineering.csv
            - name: Add Update
              if: ${{ github.event.client_payload.silent }} == "False"
              uses: ./.github/actions/generate-update
              with: 
                board: scrutineering
                time: ${{ github.event.client_payload.time }}
            - name: Push to Git
              run: |
                git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
                git config --global user.name "github-actions[bot]"
                git add *
                git commit -m"[BOT] Scrutineering Update ${GITHUB_RUN_ID}"
                git push
    github-pages-deploy:
        runs-on: ubuntu-latest
        needs: [scutineering-update]
        permissions:
            contents: write
        steps:
          - name: Checkout Source Repo
            uses: actions/checkout@v2
            with: 
                ref: 'dev'
          - name: Build
            uses:  jeffreytse/jekyll-deploy-action@v0.3.1
            with:
              provider: 'github'
              token: ${{ secrets.GITHUB_TOKEN }}
              branch: 'gh-pages'
